export const DETAIL_BEGIN = 'DETAIL_BEGIN'
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS'
export const DETAIL_FAILURE = 'DETAIL_FAILURE'

export const COMMENT_BEGIN = 'COMMENT_BEGIN'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILURE = 'COMMENT_FAILURE'

export const LIKE_ARTICLE_BEGIN = 'LIKE_ARTICLE_BEGIN'
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS'
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE'

export const DISLIKE_ARTICLE_BEGIN = 'DISLIKE_ARTICLE_BEGIN'
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS'
export const DISLIKE_ARTICLE_FAILURE = 'DISLIKE_ARTICLE_FAILURE'

export const LIKE_COMMENT_BEGIN = 'LIKE_COMMENT_BEGIN'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAILURE = 'LIKE_COMMENT_FAILURE'

export const DISLIKE_COMMENT_BEGIN = 'DISLIKE_COMMENT_BEGIN'
export const DISLIKE_COMMENT_SUCCESS = 'DISLIKE_COMMENT_SUCCESS'
export const DISLIKE_COMMENT_FAILURE = 'DISLIKE_COMMENT_FAILURE'

export const USER_VOTESYSTEM_BEGIN = 'USER_VOTESYSTEM_BEGIN'
export const USER_VOTESYSTEM_SUCCESS = 'USER_VOTESYSTEM_SUCCESS'
export const USER_VOTESYSTEM_FAILURE = 'USER_VOTESYSTEM_FAILURE'
