# Generated by Django 4.0.3 on 2022-03-25 09:17

import ckeditor_uploader.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('subheading', models.CharField(max_length=80, verbose_name='subheading')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateField(auto_now=True, verbose_name='created')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('image', models.ImageField(upload_to=core.models.article_image_path, verbose_name='image')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='slug')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('article_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Deny', 'Deny')], default=('Pending', 'Pending'), max_length=50, verbose_name='choices')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='comment')),
                ('comment_created_at', models.DateField(auto_now=True, verbose_name='created')),
                ('comment_status', models.BooleanField(default=True, verbose_name='status')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_article', to='core.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('comment_created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoteSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], verbose_name='vote')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
